### ISSUE TITLE
print() is a function in Python 3

### ISSUE THREAD

**Issue by cclauss** [lzfelix/pyStrings#1]
flake8 testing of https://github.com/lzfelix/pyStrings on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./levenshtein.py:302:64: E999 SyntaxError: invalid syntax
    print "Aligning %s and %s using Needleman-Wunsch algorithm:" % (s1, s2)
                                                               ^
1     E999 SyntaxError: invalid syntax
1
```

**Comment by lzfelix** [comment]
Hello! Well, this is a very old project that I developed in 2015. By taking a look at this string, it seems that the code was written for Python 2.x.

If you want to port it to Python 3.x or to fix linting issues, PR are more than welcome, as currently I am focusing on another project. 😄
